name: Deploy Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - features/*
  pull_request:
    branches:
      - main

env:
  RESOURCES_PREFIX: devopsoh90
defaults:
  run:
    working-directory: iac/terraform

jobs:
  preview:
    runs-on: ubuntu-latest
    outputs:
      TFPLAN_EXITCODE: ${{ steps.tfplan.outputs.exitcode }}

    steps:

    - uses: actions/checkout@v3.5.0
      name: Checkout code

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      run: |
          az login --service-principal --username "${{ secrets.ARM_CLIENT_ID }}" --password "${{ secrets.ARM_CLIENT_SECRET }}" --tenant "${{ secrets.ARM_TENANT_ID }}"
          az account set --subscription "${{ secrets.ARM_SUBSCRIPTION_ID }}"
    
    - name: Terraform Init
      run: |
        terraform init -backend-config=storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config=container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" -backend-config=key="${{ secrets.TFSTATE_KEY }}" -backend-config=resource_group_name="${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}"

    - name: Terraform Plan
      id: tfplan
      run: |
          terraform plan --detailed-exitcode -var="location=${{ secrets.LOCATION }}" -var="resources_prefix=${RESOURCES_PREFIX}"

  deploy:
    runs-on: ubuntu-latest
    needs: preview
    if: needs.preview.outputs.TFPLAN_EXITCODE == 2
    steps:

    - uses: actions/checkout@v3.5.0
      name: Checkout code

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      run: |
          az login --service-principal --username "${{ secrets.ARM_CLIENT_ID }}" --password "${{ secrets.ARM_CLIENT_SECRET }}" --tenant "${{ secrets.ARM_TENANT_ID }}"
          az account set --subscription "${{ secrets.ARM_SUBSCRIPTION_ID }}"
    
    - name: Terraform Init
      run: |
        terraform init -backend-config=storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config=container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" -backend-config=key="${{ secrets.TFSTATE_KEY }}" -backend-config=resource_group_name="${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}"

    - name: Terraform Apply
      run: |
         terraform apply --auto-approve -var="location=${{ secrets.LOCATION }}" -var="resources_prefix=${RESOURCES_PREFIX}"