name: Check and preview Terraform

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - iac/terraform/**

jobs:
  check-and-preview-bicep:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/terraform
    steps:

    - uses: actions/checkout@v3.5.0
      name: Checkout code

    - name: Azure Login
      run: |
          az login --service-principal --username "${{ secrets.ARM_CLIENT_ID }}" --password "${{ secrets.ARM_CLIENT_SECRET }}" --tenant "${{ secrets.ARM_TENANT_ID }}"
          az account set --subscription "${{ secrets.ARM_SUBSCRIPTION_ID }}"

    - name: Terraform lint
      run: |
          terraform fmt -check
          if [ $? -ne 0 ]; then
              _error "Terraform files are not properly formatted!"
              exit 1
          fi

    - name: Terraform Init
      run: |
        terraform init -backend-config=storage_account_name="${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}" -backend-config=container_name="${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}" -backend-config=key="${{ secrets.TFSTATE_KEY }}" -backend-config=resource_group_name="${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}"

    - name: Terraform Disable Local Backend
      run: |
        terraform init -backend=false

    - name: Terraform Disable Local Backend
      run: |
        terraform validate