name: User Profile CI

on: 
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/userprofile-ci.yml
      - apis/userprofile/**
  push:
    branches:
      - main
    #   - features/*
    # paths:
    #   - .github/workflows/userprofile-ci.yml
    #   - apis/userprofile/**

jobs:
  build_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/userprofile

    steps:
      - uses: actions/checkout@v3.5.0
        name: Checkout code

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - run: npm ci
        name: Install packages
      
      - run: npm build
        name: Build

      - run: npm run test
        name: Tests