name: User Profile CI

on: 
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/userprofile-ci.yml
      - apis/userprofile/**
  push:
    branches:
      - main
    #   - features/*
    # paths:
    #   - .github/workflows/userprofile-ci.yml
    #   - apis/userprofile/**

jobs:
  build_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/userprofile

    steps:
      - uses: actions/checkout@v3.5.0
        name: Checkout code

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - run: npm ci
        name: Install packages
      
      - run: npm build
        name: Build

      - run: npm run test
        id: node-tests
        name: Tests
    
  comment:
    runs-on: ubuntu-latest
    if: ${{ failure() && needs.build_tests.steps.node-tests.outcome != 'success' }}
    needs: build_tests
    steps:
        # - uses: actions/checkout@v3.5.0
        #   name: Checkout code

        - name: Add comment to PR
          uses: actions/github-script@v6
          with:
            script: |
              const body = `
                          ### Unit Test \`failure ❌\`
                          <details>
                          <summary>Workflow details</summary>

                          Workflow name: \`\${{ github.workflow }}\`
                          Action: \`\${{ github.event_name }}\`
                          Job: \`\${{ github.job }}\`
                          PR: #\${{ github.event.number }}
                          </details>

                          Test details: [Run #\${{ github.run_id }}](\${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }})
                          Pusher: @\${{ github.actor }}
                          `;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              })

        # - uses: actions/github-script@v3
        #   with:
        #     github-token: ${{ github.token }}
        #     script: |
        #       github.issues.createComment({
        #         issue_number: ${{ github.event.number }},
        #         owner: context.repo.owner,
        #         repo: context.repo.repo,
        #         body: '👋 Thanks for reporting!'
        #       })
            
        # - run:  gh pr comment ${{ github.event.number }} --body "This looks great, lets get it deployed."
        #   env:
        #     GH_TOKEN: ${{ github.token }}
        #   name: GitHub Pull Request Comment

      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'heelo'
      #       })